from django.urls import include, path
from . import views, login_views, ca_views, user_views, driver_views

urlpatterns = [
    path('',views.hello, name='welcome'),
    path('u/', login_views.ulogin, name='ulogin'),
    path('d/', login_views.dlogin, name='dlogin'),
    path('ucheck/', login_views.ucheck, name='ucheck'),
    path('dcheck/', login_views.dcheck, name='dcheck'),
    path('usignup/', ca_views.usignup, name='usignup'),
    path('dsignup/', ca_views.dsignup, name='dsignup'),
    path('ucreate/', ca_views.ucreate, name='ucreate'),
    path('dcreate/', ca_views.dcreate, name='dcreate'),
    path('user/<username>/', user_views.hello, name='user'),
    path('driver/<username>/', driver_views.hello, name='driver'),
    path('user/<username>/<id>/uview/', user_views.uview, name='uview'),
    path('driver/<username>/view/', driver_views.viewride, name='dview'),
    path('user/<username>/r/', user_views.requestride, name='ureq'),
    path('user/<username>/s/', user_views.searchride, name='usearch'),
    path('user/<username>/<time1>/<time2>/<num>/<dest>', user_views.refreshride, name='uref'),
    path('user/<username>/<id>/ue/', user_views.uedit, name='uedit'),
    path('user/<username>/<num>/se/', user_views.sedit, name='sedit'),
    path('user/<username>/scancle/', user_views.scancel, name='scancel'),
    path('driver/<username>/<id>/complete/', driver_views.complete, name='complete'),
    path('user/<username>/<id>/change/', user_views.uchange, name='uchange'),
    path('user/<username>/sretrieve/', user_views.sretrieve, name='sretrieve'),
    path('user/<username>/history/', driver_views.history, name='dhistory'),
    path('user/<username>/de/', driver_views.edit, name='dedit'),
    path('user/<username>/dupdate/', driver_views.updata, name='dupdate'),
    path('user/<username>/user_uncompleted/', user_views.uride, name='uride'),
    path('user/<username>/utable/', user_views.utable, name='utable'),
    path('user/uquery',user_views.query, name='query'),
    path('user/<username>/retreive/', driver_views.dretreive, name='dretreive'),
]